Repository 20250123-SSG/final-yesul, pull requests merged in 2025-07, with the labels that each got.

#39 Feat/17-admin-userInfo (관리자 페이지 회원관리 구현)
  src/main/java/com/yesul/admin/model/dto/alcohol/AlcoholDetailAdminDto.java
  src/main/java/com/yesul/admin/model/dto/alcohol/AlcoholListAdminDto.java
  src/main/java/com/yesul/admin/model/dto/auth/LoginAdmin.java
  src/main/java/com/yesul/admin/model/dto/auth/LoginAdminDto.java
  src/main/java/com/yesul/admin/model/dto/board/BoardAdminDto.java
  src/main/java/com/yesul/admin/model/dto/review/ReviewDetailAdminDto.java
  src/main/java/com/yesul/admin/model/dto/review/ReviewImageAdminDto.java
  src/main/java/com/yesul/admin/model/dto/review/ReviewListAdminDto.java
  src/main/java/com/yesul/admin/model/dto/userInfo/UserInfoListAdminDto.java
  src/main/java/com/yesul/admin/model/entity/Admin.java
  src/main/java/com/yesul/admin/model/entity/Board.java
  src/main/java/com/yesul/admin/model/enums/StatusType.java
  src/main/java/com/yesul/admin/repository/AdminRepository.java
  src/main/java/com/yesul/admin/repository/LoginAdminRepository.java
  src/main/java/com/yesul/admin/repository/UserInfoAdminRepository.java
  src/main/java/com/yesul/admin/service/AdminService.java
  src/main/java/com/yesul/admin/service/UserDetailsServiceImpl.java
  src/main/java/com/yesul/config/SecurityConfig.java
  src/main/java/com/yesul/exception/handler/UpdateFailedException.java
  src/main/resources/static/asserts/js/chatapp.js
  src/main/resources/static/asserts/js/data/apexchart-page-data.js
  src/main/resources/static/asserts/js/data/ecommerce-chart-data.js
  src/main/resources/static/asserts/js/material-icon.js
  src/main/resources/templates/admin/login.html
  src/main/resources/templates/fragments/admin/head.html
  src/main/resources/templates/fragments/admin/script.html
  src/test/java/com/yesul/admin/PasswordEncodingTest.java
Labels: enhancement

#47 feat: ncp-upload 기능 추가
  src/main/java/com/yesul/config/S3Config.java
  src/main/java/com/yesul/utill/HtmlImageExtractor.java
  src/main/java/com/yesul/utill/ImageUpload.java
  src/main/resources/application.yml
Labels: enhancement

#58 Feat/55 user communuty update (게시글 수정 기능 추가)
  src/main/java/com/yesul/community/controller/PostController.java
  src/main/java/com/yesul/community/model/entity/Post.java
  src/main/java/com/yesul/community/service/PostService.java
  src/main/java/com/yesul/community/service/PostServiceImpl.java
  src/main/resources/templates/community/postDetail.html
  src/main/resources/templates/community/postEdit.html
  src/main/resources/templates/community/postRecipe.html
Labels: enhancement

#62 Feat/25 user mypage
  src/main/java/com/yesul/user/controller/UserController.java
  src/main/java/com/yesul/user/model/dto/UserPasswordRequestDto.java
  src/main/java/com/yesul/user/model/dto/UserPasswordResetDto.java
  src/main/java/com/yesul/user/model/dto/UserResignDto.java
  src/main/java/com/yesul/user/model/dto/UserUpdateDto.java
  src/main/java/com/yesul/user/model/entity/User.java
  src/main/java/com/yesul/user/service/CustomUserDetailsService.java
  src/main/java/com/yesul/user/service/EmailAsyncService.java
  src/main/java/com/yesul/user/service/PasswordAsyncService.java
  src/main/java/com/yesul/user/service/RegistrationAsyncService.java
  src/main/java/com/yesul/user/service/UserService.java
  src/main/java/com/yesul/user/service/UserServiceImpl.java
  src/main/resources/static/assets/css/style.css
  src/main/resources/static/assets/img/app/default_profile.jpg
  src/main/resources/templates/user/regist.html
  src/main/resources/templates/user/reset-password.html
  src/main/resources/templates/user/resign.html
  src/main/resources/templates/user/user-edit.html
  src/main/resources/templates/user/user-profile.html
Labels: enhancement

#87 Feat/77-admin-TOTP
  build.gradle
  src/main/java/com/yesul/admin/model/dto/auth/LoginAdmin.java
  src/main/java/com/yesul/admin/model/entity/Admin.java
  src/main/java/com/yesul/admin/service/UserDetailsServiceImpl.java
  src/main/java/com/yesul/config/OtpConfig.java
  src/main/java/com/yesul/config/SecurityConfig.java
  src/main/java/com/yesul/login/controller/AdminLoginController.java
  src/main/java/com/yesul/login/handler/AdminLoginSuccessHandler.java
  src/main/java/com/yesul/login/service/AdminOtpService.java
  src/main/resources/static/asserts/css/style.css
  src/main/resources/static/asserts/img/bg/3.jpg
  src/main/resources/templates/admin/login.html
  src/main/resources/templates/admin/otp.html
  src/test/java/com/yesul/admin/GoogleAuthenticatorTest.java
Labels: enhancement

#113 Feat/84-admin-monitoring
  .DS_Store
  src/main/java/com/yesul/admin/controller/AdminController.java
  src/main/java/com/yesul/admin/model/dto/AdminLoginLogDto.java
  src/main/java/com/yesul/admin/model/entity/AdminLoginLog.java
  src/main/java/com/yesul/admin/repository/AdminLoginLogRepository.java
  src/main/java/com/yesul/admin/service/AdminService.java
  src/main/java/com/yesul/common/filter/SystemMonitoringFilter.java
  src/main/java/com/yesul/community/model/dto/PostResponseDto.java
  src/main/java/com/yesul/community/repository/PostRepository.java
  src/main/java/com/yesul/community/repository/PostRepositoryCustom.java
  src/main/java/com/yesul/community/repository/PostRepositoryImpl.java
  src/main/java/com/yesul/config/SecurityConfig.java
  src/main/java/com/yesul/login/controller/AdminLoginController.java
  src/main/java/com/yesul/login/model/dto/AdminLoginLogDto.java
  src/main/java/com/yesul/login/service/AdminOtpService.java
  src/main/java/com/yesul/monitoring/controller/MonitoringController.java
  src/main/java/com/yesul/monitoring/model/dto/DashboardDto.java
  src/main/java/com/yesul/monitoring/repository/AdminLoginLogRepository.java
  src/main/java/com/yesul/user/model/dto/UserListDto.java
  src/main/resources/application-local.yml
  src/main/resources/static/asserts/img/favicon/favicon.ico
  src/main/resources/static/asserts/img/favicon/favicon.png
  src/main/resources/templates/admin/dashboard.html
  src/main/resources/templates/admin/login.html
  src/main/resources/templates/fragments/admin/head.html
  src/main/resources/templates/fragments/admin/header.html
  src/main/resources/templates/fragments/admin/script.html
  src/main/resources/templates/fragments/admin/sidebar.html
  src/main/resources/templates/fragments/user/feature.html
Labels: enhancement

#121 Feat/97-admin-alcohol
  src/main/java/com/yesul/alcohol/controller/AdminAlcoholController.java
  src/main/java/com/yesul/alcohol/model/dto/AlcoholDto.java
  src/main/java/com/yesul/alcohol/repository/AlcoholRepository.java
  src/main/java/com/yesul/alcohol/repository/AlcoholRepositoryCustom.java
  src/main/java/com/yesul/alcohol/repository/AlcoholRepositoryImpl.java
  src/main/java/com/yesul/alcohol/service/AlcoholService.java
  src/main/resources/templates/admin/alcohol/detail.html
  src/main/resources/templates/admin/alcohol/list.html
  src/main/resources/templates/admin/product/list.html
  src/main/resources/templates/fragments/admin/script.html
  src/main/resources/templates/fragments/admin/sidebar.html
Labels: enhancement

#136 Refactor/127 chat and notification view
  src/main/java/com/yesul/chatroom/config/ChatSocketHandler.java
  src/main/java/com/yesul/chatroom/controller/admin/AdminChatRoomController.java
  src/main/java/com/yesul/chatroom/model/dto/response/MessageResponseDto.java
  src/main/java/com/yesul/chatroom/model/entity/ChatRoom.java
  src/main/java/com/yesul/chatroom/service/MessageServiceImpl.java
  src/main/java/com/yesul/notification/controller/NotificationController.java
  src/main/java/com/yesul/notification/handler/NotificationHandler.java
  src/main/java/com/yesul/notification/model/dto/request/CreateNotificationRequestDto.java
  src/main/java/com/yesul/notification/model/dto/response/NotificationResponseDto.java
  src/main/java/com/yesul/notification/service/NotificationServiceImpl.java
  src/main/resources/templates/admin/admin-chat.html
  src/main/resources/templates/fragments/admin/notify-sidebar.html
  src/main/resources/templates/fragments/user/header.html
  src/main/resources/templates/user/user-chat.html
Labels: documentation

#147 Feat/141 chat and notification refactoring
  build.gradle
  src/main/java/com/yesul/chatroom/controller/admin/AdminChatRoomController.java
  src/main/java/com/yesul/chatroom/controller/common/ChatImageController.java
  src/main/java/com/yesul/chatroom/controller/common/TempMessageController.java
  src/main/java/com/yesul/chatroom/controller/user/ChatController.java
  src/main/java/com/yesul/chatroom/model/dto/request/MessageRequestDto.java
  src/main/java/com/yesul/chatroom/model/dto/response/AdminChatRoomsResponse.java
  src/main/java/com/yesul/chatroom/model/dto/response/ChatRoomResult.java
  src/main/java/com/yesul/chatroom/model/dto/response/ChatRoomSummaryResponse.java
  src/main/java/com/yesul/chatroom/model/dto/response/MessageResponseDto.java
  src/main/java/com/yesul/chatroom/repository/MessageRepository.java
  src/main/java/com/yesul/chatroom/repository/MessageRepositoryCustom.java
  src/main/java/com/yesul/chatroom/repository/MessageRepositoryImpl.java
  src/main/java/com/yesul/chatroom/service/TempMessageService.java
  src/main/java/com/yesul/chatroom/service/TempMessageServiceImpl.java
  src/main/java/com/yesul/config/SecurityConfig.java
  src/main/java/com/yesul/config/SwaggerConfig.java
  src/main/java/com/yesul/config/WebsocketConfig.java
  src/main/java/com/yesul/exception/handler/AuthenticationNotFoundException.java
  src/main/java/com/yesul/notification/controller/NotificationController.java
  src/main/java/com/yesul/notification/controller/NotificationViewController.java
  src/main/java/com/yesul/notification/model/entity/Notification.java
  src/main/java/com/yesul/notification/repository/NotificationRepository.java
  src/main/java/com/yesul/notification/service/NotificationServiceImpl.java
  src/main/resources/application.yml
Labels: enhancement

#164 Fix/163 websocket refactoring
  src/main/java/com/yesul/config/WebsocketConfig.java
Labels: bug

#165 Fix/163 websocket refactoring
  src/main/resources/templates/admin/admin-chat.html
  src/main/resources/templates/fragments/admin/notify-sidebar.html
  src/main/resources/templates/fragments/user/header.html
  src/main/resources/templates/user/user-chat.html
Labels: enhancement

#167 Fix/163 websocket refactoring
  src/main/java/com/yesul/chatroom/model/dto/response/MessageResponseDto.java
  src/main/resources/templates/admin/admin-chat.html
  src/main/resources/templates/fragments/user/header.html
  src/main/resources/templates/user/user-chat.html
Labels: enhancement

#168 Fix/163 websocket refactoring
  src/main/resources/application-dev.yml
Labels: bug

#170 Feat/98-admin-event
  src/main/java/com/yesul/admin/controller/AdminController.java
  src/main/java/com/yesul/alcohol/controller/AdminAlcoholController.java
  src/main/java/com/yesul/config/SecurityConfig.java
  src/main/java/com/yesul/event/controller/EventFormController.java
  src/main/java/com/yesul/event/model/dto/EventFormRequestDto.java
  src/main/java/com/yesul/event/model/dto/EventListDto.java
  src/main/java/com/yesul/event/model/entity/EventList.java
  src/main/java/com/yesul/event/repository/EventListRepository.java
  src/main/java/com/yesul/event/service/EventService.java
  src/main/java/com/yesul/exception/handler/UnauthorizedAccessException.java
  src/main/java/com/yesul/notice/controller/NoticeController.java
  src/main/java/com/yesul/notice/repository/NoticeRepository.java
  src/main/java/com/yesul/notice/service/NoticeServiceImpl.java
  src/main/resources/application-local.yml
  src/main/resources/templates/admin/notice/detail.html
  src/main/resources/templates/admin/notice/regist.html
Labels: enhancement
